# Generated by Django 6.1.1 on 2026-09-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationmodel",
            name="parameters",
            field=models.JSONField(default=dict),
        ),
    ]
