# Generated by Django 6.1.1 on 2026-09-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0003_recommendationresult_unique_recommendation_result"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recommendationmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("algorithm",),
                name="unique_active_model_per_algorithm",
            ),
        ),
    ]
