# Generated by Django 6.1.1 on 2026-09-24 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
